### ISSUE TITLE
Reset EEPROM to factory defaults causes Chrysalis to hang

### ISSUE THREAD

**Issue by cdwilson** [keyboardio/Chrysalis#1056]
**Describe the bug**
When I click the "Reset EEPROM to factory defaults", Chrysalis just hangs with the orange spinner:

<img width="2559" alt="image" src="https://user-images.githubusercontent.com/14631/191821159-fbc6c033-a1f2-4f7a-a3b3-6904dacbfeb7.png">

After a couple min, I had to kill the app.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Chrysalis Version: 0.11.2

**Comment by cdwilson** [comment]
BTW, when I restart Chrysalis, the app connects to the keyboard OK (layout is read), but each time I try to reset the EEPROM, the app hangs.

**Comment by algernon** [comment]
Yeah, this is a known problem - but didn't have an issue open about it till now, thanks!.

This happens because Chrysalis wants to wait for the eeprom reset to complete, but for a number of reasons, the firmware reboots the keyboard after resetting eeprom, before sending a reply back to Chrysalis. So Chrysalis keeps waiting for a loooong time.

I have an idea how to fix it, just didn't get around to it yet.
