### ISSUE TITLE
Shift to + Lock to combination not working

### ISSUE THREAD

**Issue by btmask** [keyboardio/Chrysalis#291]
Changes:
-Copied layer 0 into layer 3.
-Copied layer 1 into layer 4.
-Copied layer 2 into layer 5.
-Set 3 as default.
-Changed palm keys on layer 3 to "shift to layer 5".
-Changed the "A" key on layer 5 to "lock to layer 4". (to mimic num on default layer)
-Changed the "A" key on layer 4 to "lock to layer 3". in order to go back to default.

Result:
-Num on default layer works, locks to layer 4, and the left part is working.
-When I "palm button" + "A" it becomes buggy, some numbers work oddly and sometimes writes 50 and most times doesn't input anything at all, this happens both in left and right sides so I assume I'm on a weird layer 4, signs appear to work, and "A" doesn't lock to default apparently unless I do it with palm as if I was on layer 3. and sometimes I got issues coming back to regular layout so I disabled this.

![image](https://user-images.githubusercontent.com/26680091/52300894-5aac2400-2989-11e9-8897-47a354c105fa.png)
![image](https://user-images.githubusercontent.com/26680091/52300906-5f70d800-2989-11e9-9c7a-91f8c27303db.png)
![image](https://user-images.githubusercontent.com/26680091/52300911-61d33200-2989-11e9-8914-3882579e7405.png)

**Comment by algernon** [comment]
The problem here is that the way layers work is perhaps not as one would expect: when you "lock a layer", that does not turn all other layers off, it just turns said layer on. Any other layers will remain active too. That is, layers stack, they do not replace each other.

So when on layer 5, you have a `LockLayer(4)`, that will enable layer 4, but keep 5 active too.

Mind you, the behaviour described is still strange, and I'll have to investigate further. But the issue is not in Chrysalis. I'm keeping the issue open until the root cause is found regardless.
