### ISSUE TITLE
Can't use Chrysalis with EEPROMKeymaps disabled, Colormap enabled

### ISSUE THREAD

**Issue by joedevivo** [keyboardio/Chrysalis#496]
**Describe the bug**

I'm trying to add colormaps for my existing firmware layers. @algernon suggested disabling EEPROMKeymaps to do so, but when I do that, Chrysalis can see my keyboard, but can't connect to it and wants to update the firmware.

I've pushed the firmware sketch I'm working from [here](https://github.com/joedevivo/Model01-Firmware/blob/colormap-bug/Model01-Firmware.ino) in case the problem is on my side.

**To Reproduce**
1. Flash Model 01 with EEPROMKeymaps disabled, Colormap enabled
2. Open Chrysalis
3. Connect to that keyboard
4. See error requesting firmware update

**Expected behavior**
I expected to see grayed out keymaps and editable colormaps in the editor

**Screenshots**
![Screenshot 2020-04-03 06 48 28](https://user-images.githubusercontent.com/55951/78367567-2628fd80-7577-11ea-8ae3-7d935b127dd0.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Chrysalis Version: 0.7.4

**Additional context**
If there's a way to let me assign specific LED Effects to different layers, I'd prefer that over colormap and it could be done in the firmware as well.

**Comment by algernon** [comment]
I thought this would be a quick fix, just letting Chrysalis go to the Editor screen when there's no keymap. Turns out, it's considerably more involved, because the Editor screen relies on having a keymap available for a number of things, including layers.

Nevertheless, I have a reasonable idea how to fix this without hacking many things around.
