### ISSUE TITLE
Update dependency to versions which still get security fixes

### ISSUE THREAD

**Issue by darix** [keyboardio/Chrysalis#600]
e.g. the electron version doesnt seems to get fixes anymore.

**Comment by algernon** [comment]
We have updated our dependencies since. We.... tend to lag behind on dependencies quite often, mostly because upgrading them has proven to be a colossal pain and time sink every single time since the inception of Chrysalis.

A reminder from time to time is appreciated, nevertheless. If we start to lag behind again, please feel free to open another issue. Thanks!
