### ISSUE TITLE
Add all Windows layouts

### ISSUE THREAD

**Issue by necsoiu** [keyboardio/Chrysalis#633]
Please add all Windows layouts. 

For example  I'm using "Romanian (Programmers)".

Thank you very much.

**Comment by algernon** [comment]
Is [this](https://unicode-org.github.io/cldr-staging/charts/latest/keyboards/layouts/ro.html#ro-t-k0-windows-extended) the layout you'd want?

The problem with enabling _all_ windows layouts is that it's a lot of layouts, making the already crowded dropdown even longer. We can do that, but I'd strongly prefer doing so while we improve the UX of the layout selection widget too.

**Comment by algernon** [comment]
I _think_ I figured out a way to do this somewhat reasonably, but it requires a lot of massaging to make things appear consistent. The main problem is that the name of the various layouts in the CLDR database aren't consistent. For example, there's "United Kingdom", "English (India)", "United States-International", and "US". All of these are variations of an English layout, yet only one of them has "English" in its name. Out of all the `en-` layouts, only the India variant has english in it's name. There are similar issues with many other languages, too.

So what we can do, is have a mapping between the language code (`en`, etc) and the language name (`English`), and group layouts by filename, using the language name as a header. That still won't be perfect, because to find the "English UK" variant, you'll need to look for "United Kingdom" under the "English" header... oh! If we make the headers selectable too, then I guess that'll work...

**Comment by necsoiu** [comment]
> Is [this](https://unicode-org.github.io/cldr-staging/charts/latest/keyboards/layouts/ro.html#ro-t-k0-windows-extended) the layout you'd want?
> 
> The problem with enabling _all_ windows layouts is that it's a lot of layouts, making the already crowded dropdown even longer. We can do that, but I'd strongly prefer doing so while we improve the UX of the layout selection widget too.

 YES.  This is it. :) I would be very grateful if you could add it.
