### ISSUE TITLE
0.8.3-Snapshot - PrSc (Print Screen) no longer available in Chrysalis

### ISSUE THREAD

**Issue by tmarzolf** [keyboardio/Chrysalis#655]
**Describe the bug**
Print Screen no longer found in Pick a Key graphical tool or menus

**To Reproduce**
1. Go to Pick a Key
2. Print Screen is not found as a valid Standard Key - even though it is on a standard keyboard layout

**Expected behavior**
Print Screen able to be configured from Chrysalis either from Pick a Key or from a menu

**Screenshots**

![image](https://user-images.githubusercontent.com/63314904/106627982-5189c980-6547-11eb-8929-60419710abcd.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Chrysalis Version: 0.8.3 Snapshot

**Additional context**

**Comment by tmarzolf** [comment]
Workaround is to use custom key code 70

`{"code":70,"label":{"base":{"full":"Print Screen","1u":"PrSc"}}}`

**Comment by algernon** [comment]
Oops!

The major reason it isn't there is because the key picker was originally displayed at the bottom, rather than in a popup dialog, and we wanted to save vertical space (that's why the Fx keys are on the right side too, rather than on top like on a standard keyboard). At that iteration, we had another way to select Print Screen, and a couple of other keys, which we no longer do.

I'll rearrange the selector, and add back print screen too. Thanks!

**Comment by algernon** [comment]
Just pushed an update to master:

![Screenshot from 2021-02-15 22-01-49](https://user-images.githubusercontent.com/17243/107992926-07d6bf80-6fda-11eb-9592-6c6c5d8197f8.png)
