### ISSUE TITLE
Ideas to improve the Preferences screen

### ISSUE THREAD

**Issue by algernon** [keyboardio/Chrysalis#843]
While the Preferences screen has seen some great improvements recently (such as being turned into a tabbed page, thanks to @obra), it still feels rather dry, and not very user friendly.

We do not have adequate amounts of help text and descriptions to explain what each thing does. For example, a `[x] Dark Mode` toggle button just hanging there is neither descriptive, nor very elegant. The language selection dropdown with its darker background, and spanning the whole width of the panel isn't nice, either.

The "Developer tools" page is also very short on information. It's just two pretty non-descript toggles.

I propose we overhaul the whole thing, adding more help text. Rather than a `[x] Dark Mode` toggle, for example, we'd have a paragraph or two, and an `Enable / Disable` toggle, where the text changes depending on state, too. That feels way friendlier.

I have a couple of other ideas, and I'll be posting screenshots of mockups, once I get there, so we can discuss how to improve Preferences further.

**Comment by obra** [comment]
I think we're probably looking for a sentence rather than a paragraph.  And
having the primary text change based on the toggle is...not necessarily a
good thing. It can get super confusing to manage.

I agree 100% that the ultra-wide dropdowns from the MUI guidelines don't
feel right. But the narrow dropdowns we have also feel bad.  I wonder if
there are desktop MUI apps that do this well. Or there are other MUI themes
that do.

**Comment by Rom1deTroyes** [comment]
For the « Dark/Light theme » option, one of the best I've seen is from [postman](https://www.postman.com/) app :
![image](https://user-images.githubusercontent.com/8625432/170789599-164b1e6e-38c7-43e8-b920-96342d180397.png)

The preview is explicit enough for not having a paragraph, and the sentence can be kept simple, because the pictures decribes well what it's all about :art:
