### ISSUE TITLE
Permission denied on Model 100 bootloader device during firmware flash on LMDE 5

### ISSUE THREAD

**Issue by sruggier** [keyboardio/Chrysalis#856]
I used Chrysalis for the first time yesterday, on a relatively fresh install of LMDE 5 (Linux Mint Debian Edition, based on Debian Bullseye). It connects successfully to the keyboard during configuration, but after pressing the prog button during firmware flashing and rebooting to the keyboard's bootloader, the corresponding device is now owned by root only, and Chrysalis fails to connect.

After running `chown root:plugdev /dev/bus/usb/nnn/nnn` on the device, I was able to finish flashing the firmware.

**Comment by algernon** [comment]
This is, I believe, the same as #824, a case of not warning in advance that the bootloader has inadequate permissions. That's... hard to check in advance, but I have a few ideas. Meanwhile, you can install the `udev` rules file from [here](https://raw.githubusercontent.com/keyboardio/Chrysalis/master/static/udev/60-kaleidoscope.rules): drop it in `/etc/udev/rules.d`, run `sudo udevadm control -R` so that udev picks it up, and next time the keyboard goes into bootloader mode, it will have the correct permissions (be owned by the logged in user).
