### ISSUE TITLE
Dynamic Macros : Macros are not empty

### ISSUE THREAD

**Issue by Rom1deTroyes** [keyboardio/Chrysalis#934]
**Describe the bug**
When using the Dynamic Macros for the first time on my Atreus, there are some bulk macros already there.

**Expected behavior**
An empty list, or even better : an example macro resuming what you can do :memo: 

**Screenshots**
![image](https://user-images.githubusercontent.com/8625432/172871158-4d43a810-63f7-4777-93fd-2a558f0b8bf7.png) ![image](https://user-images.githubusercontent.com/8625432/172871257-10a8b3e4-2982-44a0-8efe-c8b5a7d3a070.png) ![image](https://user-images.githubusercontent.com/8625432/172871385-2f510a67-9796-47eb-badc-246673f5a636.png)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Chrysalis Version: 0.10.2-snapshot build from master
 
**Additional context**
I had a custom firmware build from kaleidoscope example sketch that used the eeprom to store 10 layers, and flashed the experimental firmware from Chrysalis.

**Comment by algernon** [comment]
This happens when we reuse eeprom space, when you had a firmware that used the area now reserved for dynamic macros for something else, then this happens. The proper fix here would be to clear EEPROM before doing a structured restore, as that will guarantee that we will not see garbage.

I used to be vary - and still am, to some extent - about clearing EEPROM on flash, but clearing + structural restore is the least surprising behaviour, so lets do that, and clear.

**Comment by algernon** [comment]
I have a patch that fixes this, but before we can apply that, we need to fortify the flashing process quite a bit. That'll likely take a bit of time, but it's one of my highest priorities now (for a number of reasons, not just this).

**Comment by algernon** [comment]
For reference, this depends on #941, we need to make the flashing process more reliable before it is safe to clear EEPROM as part of it.
